#!/bin/sh
set -e
if [ -f "/etc/default/pswatcher" ]
then
        . /etc/default/ps-watcher
fi

if [ -x "/etc/init.d/ps-watcher" ]; then
	update-rc.d ps-watcher defaults 40 >/dev/null
	if [ "$startup" = "1" ] && [ -f "/etc/default/pswatcher" ]; then
        	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
                	invoke-rc.d ps-watcher start || exit $?
        	else
                	/etc/init.d/ps-watcher start || exit $?
        	fi
	fi
fi
